### ISSUE TITLE
Add remarkable-tablet topic

### ISSUE THREAD

**Issue by Eeems** [eksubin/Remarkable-RSS-Feed#1]
https://remarkable.guide/devel/github.html#remarkable-tablet-topic

**Comment by eksubin** [comment]
I have added the support tags for both Remarkable 2 and the new Remarkable Pro

**Comment by Eeems** [comment]
> I have added the support tags for both Remarkable 2 and the new Remarkable Pro

That's not what I was asking for in this issue.
